### ISSUE TITLE
Broken hyperlinks in CSS/Topics/02. CSS-Presentation/homework/README.md - Problem 2

### ISSUE THREAD

**Issue by IvanParvanov** [TelerikAcademy/CSS#3]
Links should be changed to [rawHTML](https://raw.githubusercontent.com/TelerikAcademy/CSS/master/Topics/02.%20CSS-Presentation/homework/homework.html) and [rawCSS](https://raw.githubusercontent.com/TelerikAcademy/CSS/master/Topics/02.%20CSS-Presentation/homework/homework.css) or [HTML](https://github.com/TelerikAcademy/CSS/blob/master/Topics/02.%20CSS-Presentation/homework/homework.html) and [CSS](https://github.com/TelerikAcademy/CSS/blob/master/Topics/02.%20CSS-Presentation/homework/homework.css).
Minor issue, but some people might get confused :)

**Comment by cuklev** [comment]
Fixed with c0cb166754e590d5f82846688f599669e9c4ae65.
